### ISSUE TITLE
How should I can implement the interface of extImageInfoGet(const Identity& origin, ExtImageInfo& data)?

### ISSUE THREAD

**Issue by liyingcheng712** [xricht17/twpp#26]
Excuse me,I am writting a DS diver now ,and I am using your framework(twhpp).
Recently,I am trying to implement you interface "extImageInfoGet(const Identity& origin, ExtImageInfo& data)",but I have no idea about what to do, can you give me a guidance?

     Thank you very much !

**Comment by xricht17** [comment]
Hi,

I am afraid you will have to refer to the official TWAIN specification in order to properly implement a DS: [https://www.twain.org/specification/](https://www.twain.org/specification/).

TWPP is a rather thin layer that solves some common operations like memory management and instance creation. You still need to understand TWAIN to do anything more advanced, and building DS is quite advanced stuff.

**Comment by liyingcheng712** [comment]
I got it!
thank you very much
