### ISSUE TITLE
How can I notify device event when using  twpp?

### ISSUE THREAD

**Issue by liyingcheng712** [xricht17/twpp#28]
Excuse me ,I am developping my own twain driver using your frame "twpp",but I have a problem when I am planning to notify the application of the device event by using the method notifyDeviceEvent(),but it returend failed! I didn`t  know why?
could you please tell me how to notify device event correctly?
thank you very much!

**Comment by xricht17** [comment]
Hi,

That's odd. Device events are allowed in states 4 (source opened) to 7 (transfer in progress), which is essentially all possible states for a source. Maybe it is not allowed to be called while a request from the application is in progress, or the application must actually be registered to receive the device events?

Try enabling TWAIN log and see what is happening there: https://developer.dynamsoft.com/dwt/kb/2680 (I am in no way affiliated with them)
You can get `TWAINDSM.dll` here: https://github.com/twain/twain-dsm

Make sure to download the 32bit version, unless you know why you need the 64bit one. If your application supports TWAIN v2, it should be enough to simply copy `TWAINDSM.dll` into `\Windows\SysWOW64\` (or `\Windows\System32` in case of 64bit version) instead of replacing `twain_32.dll`.

**Comment by xricht17** [comment]
Hi,

Any news about the issue? Have you managed to find out what's been causing it, or at least generate the log?

**Comment by xricht17** [comment]
No response for more than 2 weeks -> closing. Please reopen or create another issue if anything new comes up.
