### ISSUE TITLE
Unable to successfully send the picture taken by the added Qml example to the test program

### ISSUE THREAD

**Issue by STDwang** [xricht17/twpp#34]
auto scanFunction1 = [this](QImage cap) {
        bmpData.clear();
		QDataStream ds(&bmpData, QIODevice::WriteOnly); ds << cap;
		notifyXferReady();
	};
	auto cancelFunction1 = [this]() {
		notifyCloseCancel();
	};
        TwGlue glue1 = { scanFunction1, cancelFunction1 };
	QtCamera* camersever = new QtCamera(QCameraInfo::defaultCamera(), nullptr, glue1);

	engine.rootContext()->setContextProperty("camersever", camersever);
	engine.addImageProvider(QLatin1String("CodeImg"), camersever->m_pImageProvider);
	const QUrl url(QStringLiteral("qrc:/main.qml"));
	QObject::connect(&engine, &QQmlApplicationEngine::objectCreated, app, [url](QObject* obj, const QUrl& objUrl) {
		if (!obj && url == objUrl) QCoreApplication::exit(-1);
		}, Qt::QueuedConnection);
    engine.load(url);
    app->exec();
1. I wrote a qml program that calls the camera to take pictures, and transfers the picture data back to the simpleds instance and saves it to bmpData
2. But notifyXferReady() does not achieve the desired effect
3. After investigation, when the widget program is running, call will be continuously called and m_state can be assigned normally, but the qml program will only be called when the program starts, and m_state has not changed.
4. I want to know how can I make it achieve the same effect as the widget？

**Comment by xricht17** [comment]
Hi @STDwang,

I am afraid I do not know QML or newer versions of Qt for that matter. I won't probably be able to help you that much.

I expect your code would go somewhere inside `SimpleDs::userInterfaceEnable` in the example DS? The only suspicious thing is `app->exec()`. Unless I am terribly mistaken, that is a blocking call. Therefore `SimpleDs::userInterfaceEnable` does not return before you call `SourceFromThis::notifyXferReady`, leading to an incorrect state transition attempt. There's a good chance that the `SourceFromThis::notifyXferReady` call returns `ReturnCode::Failure` since the source has not moved to `DsState::Enabled` state yet. The state move happens only after `SimpleDs::userInterfaceEnable` returns success.

You need to open your UI in `SimpleDs::userInterfaceEnable` in a non-blocking manner to let the function return. Then, use `SimpleDs::eventProcess` to let Qt/QML process UI events - that also has to be non-blocking, otherwise the application side would appear frozen.

**Comment by STDwang** [comment]
You are right, app->exec() is the modal display of the screen, or I can't know the setWindowModality() method like QWidget to set the window semi-modal and non-modal, but please have a way to solve this problem, thanks

**Comment by STDwang** [comment]
You are right, app->exec() is the modal display of the screen, but I don't know if the Qml program has a setWindowModality() method like QWidget to set the window semi-modal and non-modal. Do you have a way to solve this problem? Well, thanks

**Comment by STDwang** [comment]
thanks, i solved it, just need to set engine as property attribute
`static std::unique_ptr<QQmlApplicationEngine> engine`
